Get pub playbook running again
planetary-social/ansible-scripts pull request #107
Opened 2024-07-08 15:54 UTC by mplorentz

These are some various updates I made to the scripts to get one.planetary.pub healthy again after upgrading it to debian bookworm. Mostly these are dependencies that weren't automatically installed - they must come preinstalled on the newer droplets? 

Also I threw in a simple playbook for seeing how many SSB users a pub follows. I wrote it a long time ago and never committed it but it's useful for [pub invitation tracking](https://github.com/planetary-social/infrastructure/wiki/Pub-Invitation-Tracking).

2025-02-15 15:12 UTC, nbenmoody requested changes

2025-02-15 15:12 UTC, nbenmoody commented on roles/common/tasks/main.yml
>  - name: update cache
It looks like this task got orphaned somewhere in here? Do we still want this one to do something, or should we remove it?

2025-03-03 18:18 UTC, mplorentz commented on roles/common/tasks/main.yml
>  - name: update cache
I think these parameters are valid under the "Perform a dist-upgrade" task.

2025-03-10 10:14 UTC, nbenmoody approved these changes
🚢 🇮🇹

2025-03-10 10:17 UTC, nbenmoody commented on roles/common/tasks/main.yml
>    ansible.builtin.apt:
I'm still seeing a call to nothing, here, when I look it over locally, but it's also harmless, so no hold up on my part.

2025-03-11 20:57 UTC, merged